<a href="https://colab.research.google.com/github/jfaraudo/Schrodinger_Numerical/blob/main/matrix_algebra/howtoobtainorderedeigenvalues_and_eigenvectors_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. HOW TO ORDER A LIST OF NUMBERS IN AN ARRAY**

Consider the following list of numbers stored in a numpy array:

In [ ]:
import numpy as np
list_of_numbers = np.array([11, 52, 2, 16, 16, 54, 453])
print("array:",list_of_numbers)

array: [ 11  52   2  16  16  54 453]


As you can see, the list is not ordered.

We can order it using the .sort() method of Python (see https://docs.python.org/es/3.13/howto/sorting.html )
:

In [ ]:
list_of_numbers.sort()
print(list_of_numbers)

[  2  11  16  16  52  54 453]


**2. Diagonalization of a Matrix**

Diagonalization in python is easy, but unfortunatelly eigenvalues and eigenvectors are not ordered.

Let us see an example. Consider this matrix:

In [ ]:
A = np.array([[0.16,0.8,0.077], [0.5,0.04,0.1],[0.66,0.85,0.69]])

print("Matrix:")
print(A)

Matrix:
[[0.16  0.8   0.077]
 [0.5   0.04  0.1  ]
 [0.66  0.85  0.69 ]]


Let us diagonalize it:

In [ ]:
eigenValues, eigenVectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenValues)
print("\nEigenvectors (each column is an eigenvector):")
print(eigenVectors)

Eigenvalues:
[ 1.07951513 -0.53726694  0.3477518 ]

Eigenvectors (each column is an eigenvector):
[[ 0.26990512  0.75026383 -0.28634259]
 [ 0.22000091 -0.65901449 -0.15815637]
 [ 0.9374171   0.05295359  0.94498386]]


Let us show the Eigenvalues and the corresponding Eigenvectors one by one (it is like having each state with its correspoding Eigenvalue and EigenVector):

In [ ]:
for k in range(0,len(eigenValues)):

   print("EigenState",k)
   print("Eigenvalue:", eigenValues[k])
   print("Eigenvector:",eigenVectors[:,k],"\n")


EigenState 0
Eigenvalue: 1.0795151323938244
Eigenvector: [0.26990512 0.22000091 0.9374171 ] 

EigenState 1
Eigenvalue: -0.5372669368488905
Eigenvector: [ 0.75026383 -0.65901449  0.05295359] 

EigenState 2
Eigenvalue: 0.3477518044550663
Eigenvector: [-0.28634259 -0.15815637  0.94498386] 



We can also create a list putting together eigenvalues with its eigenvector:

In [ ]:
eigenstates = list(zip(eigenValues, eigenVectors.transpose()))
#print(eigenstates)
for k in range(0,len(eigenValues)):
  print("\nEigenvalue and Eigenvector of state:",k)
  print(eigenstates[k])


Eigenvalue and Eigenvector of state: 0
(1.0795151323938244, array([0.26990512, 0.22000091, 0.9374171 ]))

Eigenvalue and Eigenvector of state: 1
(-0.5372669368488905, array([ 0.75026383, -0.65901449,  0.05295359]))

Eigenvalue and Eigenvector of state: 2
(0.3477518044550663, array([-0.28634259, -0.15815637,  0.94498386]))


This looks nice, but the problem here is that the states are not ordered (imagine that the Eigenvalue is the Energy, we want to have first the ground state and then all other states).
Let us order this by values of eigenvalue (energy in quantum physics) using again the sort method:

In [ ]:
eigenstates.sort(key=lambda x: x[0])
#print(eigenstates)
for k in range(0,len(eigenValues)):
  print("\nEigenvalue and Eigenvector of state:",k)
  print(eigenstates[k])


Eigenvalue and Eigenvector of state: 0
(-0.5372669368488905, array([ 0.75026383, -0.65901449,  0.05295359]))

Eigenvalue and Eigenvector of state: 1
(0.3477518044550663, array([-0.28634259, -0.15815637,  0.94498386]))

Eigenvalue and Eigenvector of state: 2
(1.0795151323938244, array([0.26990512, 0.22000091, 0.9374171 ]))


An example of how to access the data stored in that list. For example, here we print the second eigenvalue, the third eigenvector and the third eigenvalue:

In [ ]:
print(eigenstates[1][0])

0.3477518044550663


In [ ]:
print(eigenstates[2][1])

[0.26990512 0.22000091 0.9374171 ]


In [ ]:
print(eigenstates[2][0])

1.0795151323938244


We can also extract the eigenvalue and eigenvector from this combined list:

In [ ]:
E_ordered=[]
EVector_ordered=[]
for k in range(0,len(eigenValues)):
  E_ordered.append(eigenstates[k][0])
  EVector_ordered.append(eigenstates[k][1])

show the result again

In [ ]:
for k in range(0,len(E_ordered)):
  print("\nEigenvalue and Eigenvector of state:",k)
  print(E_ordered[k])
  print(EVector_ordered[k])


Eigenvalue and Eigenvector of state: 0
-0.5372669368488905
[ 0.75026383 -0.65901449  0.05295359]

Eigenvalue and Eigenvector of state: 1
0.3477518044550663
[-0.28634259 -0.15815637  0.94498386]

Eigenvalue and Eigenvector of state: 2
1.0795151323938244
[0.26990512 0.22000091 0.9374171 ]


**Testing that everything is OK.**

For example, we can multiply the matrix by one of the eigenvectors to verify that it is really an eigenstate.

Here is the result of the matrix applied over the vector

In [ ]:
np.dot(A,EVector_ordered[1])

array([-0.09957615, -0.05499916,  0.32861984])

And here is the result of the vector multiplied by its eigenvalue

In [ ]:
np.dot(E_ordered[1],EVector_ordered[1])

array([-0.09957615, -0.05499916,  0.32861984])

**The two results are identical** as it should be, the matrix applied over an eigenvector is the same vector again multiplied by a number (the eigenvalue)