<a href="https://colab.research.google.com/github/jfaraudo/Schrodinger_Numerical/blob/main/matrix_algebra/HowToObtainOrderedEigenvalues_and_Eigenvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. HOW TO ORDER A LIST OF NUMBERS IN AN ARRAY**

Consider the following list of numbers stored in a numpy array:

In [6]:
import numpy as np
array = np.array([10, 52, 2, 16, 16, 54, 453])
print("array:",array)

array: [ 10  52   2  16  16  54 453]


As yu can see, the list is not ordered.

Let us order it. First we produce a list of the previous indices by the order they should have:

In [7]:
indices = np.argsort(array)
print("Ordered indices:",indices)

Ordered indices: [2 0 3 4 1 5 6]


And now we can use this list of ordered indices to build an ordered array

In [8]:
#create ordered array
array2=array[indices]
print("Ordered array:",array2)

Ordered array: [  2  10  16  16  52  54 453]


**2. Diagonalization of a Matrix**

Diagonalization in python is easy, but unfortunatelly eigenvalues and eigenvectors are not ordered.

Let us see an example. Consider this matrix:

In [9]:
A = np.array([[0.16,0.8,0.077], [0.5,0.04,0.1],[0.66,0.85,0.69]])

print("Matrix:")
print(A)

Matrix:
[[0.16  0.8   0.077]
 [0.5   0.04  0.1  ]
 [0.66  0.85  0.69 ]]


Let us diagonalize it:

In [12]:
eigenValues, eigenVectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenValues)
print("\nEigenvectors:")
print(eigenVectors)

Eigenvalues:
[ 1.07951513 -0.53726694  0.3477518 ]

Eigenvectors:
[[ 0.26990512  0.75026383 -0.28634259]
 [ 0.22000091 -0.65901449 -0.15815637]
 [ 0.9374171   0.05295359  0.94498386]]


This format is not very practical, let us extract the Eigenvalues and Eigenvectors one by one (it is like having each state with its correspoding Eigenvalue and EigenVector):

In [13]:
for k in range(0,len(eigenValues)):

   print("EigenState",k)
   print("Eigenvalue:", eigenValues[k])
   print("Eigenvector:",eigenVectors[:,k],"\n")


EigenState 0
Eigenvalue: 1.0795151323938244
Eigenvector: [0.26990512 0.22000091 0.9374171 ] 

EigenState 1
Eigenvalue: -0.5372669368488905
Eigenvector: [ 0.75026383 -0.65901449  0.05295359] 

EigenState 2
Eigenvalue: 0.3477518044550663
Eigenvector: [-0.28634259 -0.15815637  0.94498386] 



This looks nice, but the problem is that the states are not ordered (imagine that the Eigenvalue is the Energy, we want to have first the ground state and then all other states).

We can use the previous trick:

In [14]:
id = np.argsort(eigenValues)

Val = eigenValues[id]
Vect = eigenVectors[:,id]

print("\n Ordered EigenValues and EigenVectors\n")

for k in range(0,len(Val)):

   print("EigenState",k)
   print("Eigenvalue:", Val[k])
   print("Eigenvector:",Vect[:,k],"\n")


 Ordered EigenValues and EigenVectors

EigenState 0
Eigenvalue: -0.5372669368488905
Eigenvector: [ 0.75026383 -0.65901449  0.05295359] 

EigenState 1
Eigenvalue: 0.3477518044550663
Eigenvector: [-0.28634259 -0.15815637  0.94498386] 

EigenState 2
Eigenvalue: 1.0795151323938244
Eigenvector: [0.26990512 0.22000091 0.9374171 ] 

